version: '3.8'

services:
  backend:
    build: ./back
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./front
      args:
        REACT_APP_API_URL: http://localhost:8000
    container_name: react_app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
